
import java.awt.Color;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JOY
 */
public class Distance_Calculate extends javax.swing.JFrame {

    /**
     * Creates new form Distance_Calculate
     */
    public Distance_Calculate() {
        initComponents();
        setIcon();
        this.setTitle("Traveling Distance");
        //getContentPane().setBackground(Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        out1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox<>();
        cb2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(415, 578));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        out1.setEditable(false);
        out1.setBackground(new java.awt.Color(0, 0, 0));
        out1.setBorder(null);
        out1.setForeground(new java.awt.Color(255, 255, 255));
        out1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        out1.setFont(new java.awt.Font("Open Sans Semibold", 1, 18)); // NOI18N
        getContentPane().add(out1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 119, 30));

        jButton1.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/generate.jpg"))); // NOI18N
        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 100, 30));

        jButton2.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit button.jpg"))); // NOI18N
        jButton2.setText("Cancle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 80, 30));

        cb1.setFont(new java.awt.Font("Open Sans Semibold", 1, 14)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Brahmanbaria", "Bogra", "Gaibandha", "Noakhali", "Naogaon", "Pabna", "Rangpur" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 30));

        cb2.setFont(new java.awt.Font("Open Sans Semibold", 1, 14)); // NOI18N
        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Brahmanbaria", "Bogra", "Gaibandha", "Noakhali", "Naogaon", "Pabna", "Rangpur" }));
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });
        getContentPane().add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 160, 30));

        jLabel5.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Panel.jpg"))); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(400, 580));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String s1="", s2="";
        double y=0;
        if (cb1.getSelectedItem().toString()=="Dhaka")
        {
            if (cb2.getSelectedItem().toString()=="Brahmanbaria")
            {
                y= 112.0;
            }
            else if (cb2.getSelectedItem().toString()=="Bogra")
            {
                y= 190.8;
            }
            else if (cb2.getSelectedItem().toString()=="Gaibandha")
            {
                y= 262.9;
            }
            else if (cb2.getSelectedItem().toString()=="Noakhali")
            {
                y= 167.7;
            }
            else if (cb2.getSelectedItem().toString()=="Naogaon")
            {
                y= 239.8;
            }
            else if (cb2.getSelectedItem().toString()=="Pabna")
            {
                y= 205.1;
            }
            else if (cb2.getSelectedItem().toString()=="Rangpur")
            {
                y= 299.7;
            }
        }
        //////////////
        else if (cb1.getSelectedItem().toString()=="Brahmanbaria")
        {
            if (cb2.getSelectedItem().toString()=="Dhaka")
            {
                y= 112;
            }
            else if (cb2.getSelectedItem().toString()=="Bogra")
            {
                y= 268.1;
            }
            else if (cb2.getSelectedItem().toString()=="Gaibandha")
            {
                y= 340.1;
            }
            else if (cb2.getSelectedItem().toString()=="Noakhali")
            {
                y= 135.0;
            }
            else if (cb2.getSelectedItem().toString()=="Naogaon")
            {
                y= 317.1;
            }
            else if (cb2.getSelectedItem().toString()=="Pabna")
            {
                y= 282.4;
            }
            else if (cb2.getSelectedItem().toString()=="Rangpur")
            {
                y= 376.9;
            }

        }
        ///////////
        else if (cb1.getSelectedItem().toString()=="Bogra")
        {
            if (cb2.getSelectedItem().toString()=="Dhaka")
            {
                y= 188.5;
            }
            else if (cb2.getSelectedItem().toString()=="Brahmanbaria")
            {
                y= 268.3;
            }
            else if (cb2.getSelectedItem().toString()=="Gaibandha")
            {
                y= 71.5;
            }
            else if (cb2.getSelectedItem().toString()=="Noakhali")
            {
                y= 355.7;
            }
            else if (cb2.getSelectedItem().toString()=="Naogaon")
            {
                y= 51.5;
            }
            else if (cb2.getSelectedItem().toString()=="Pabna")
            {
                y= 121.7;
            }
            else if (cb2.getSelectedItem().toString()=="Rangpur")
            {
                y= 108.3;
            }

        }
        ////////////
        else if (cb1.getSelectedItem().toString()=="Gaibandha")
        {
            if (cb2.getSelectedItem().toString()=="Dhaka")
            {
                y= 258.5;
            }
            else if (cb2.getSelectedItem().toString()=="Brahmanbaria")
            {
                y= 338.6;
            }
            else if (cb2.getSelectedItem().toString()=="Bogra")
            {
                y= 71.7;
            }
            else if (cb2.getSelectedItem().toString()=="Noakhali")
            {
                y= 426;
            }
            else if (cb2.getSelectedItem().toString()=="Naogaon")
            {
                y= 116.5;
            }
            else if (cb2.getSelectedItem().toString()=="Pabna")
            {
                y= 193.2;
            }
            else if (cb2.getSelectedItem().toString()=="Rangpur")
            {
                y= 76.6;
            }

        }
        ////////////
        else if (cb1.getSelectedItem().toString()=="Noakhali")
        {
            if (cb2.getSelectedItem().toString()=="Dhaka")
            {
                y= 179.1;
            }
            else if (cb2.getSelectedItem().toString()=="Brahmanbaria")
            {
                y= 138;
            }
            else if (cb2.getSelectedItem().toString()=="Bogra")
            {
                y= 355.1;
            }
            else if (cb2.getSelectedItem().toString()=="Gaibandha")
            {
                y= 427.2;
            }
            else if (cb2.getSelectedItem().toString()=="Naogaon")
            {
                y= 404.1;
            }
            else if (cb2.getSelectedItem().toString()=="Pabna")
            {
                y= 369.4;
            }
            else if (cb2.getSelectedItem().toString()=="Rangpur")
            {
                y= 464;
            }

        }
        ////////////
        else if (cb1.getSelectedItem().toString()=="Naogaon")
        {
            if (cb2.getSelectedItem().toString()=="Dhaka")
            {
                y= 237.5;
            }
            else if (cb2.getSelectedItem().toString()=="Brahmanbaria")
            {
                y= 317.3;
            }
            else if (cb2.getSelectedItem().toString()=="Bogra")
            {
                y= 51.5;
            }
            else if (cb2.getSelectedItem().toString()=="Gaibandha")
            {
                y= 116.5;
            }
            else if (cb2.getSelectedItem().toString()=="Noakhali")
            {
                y= 404.7;
            }
            else if (cb2.getSelectedItem().toString()=="Pabna")
            {
                y= 131.4;
            }
            else if (cb2.getSelectedItem().toString()=="Rangpur")
            {
                y= 153.3;
            }

        }
        ////////////
        else if (cb1.getSelectedItem().toString()=="Pabna")
        {
            if (cb2.getSelectedItem().toString()=="Dhaka")
            {
                y= 202.7;
            }
            else if (cb2.getSelectedItem().toString()=="Brahmanbaria")
            {
                y= 282.2;
            }
            else if (cb2.getSelectedItem().toString()=="Bogra")
            {
                y= 121.8;
            }
            else if (cb2.getSelectedItem().toString()=="Gaibandha")
            {
                y= 193.2;
            }
            else if (cb2.getSelectedItem().toString()=="Noakhali")
            {
                y= 369.8;
            }
            else if (cb2.getSelectedItem().toString()=="Naogaon")
            {
                y= 131.5;
            }
            else if (cb2.getSelectedItem().toString()=="Rangpur")
            {
                y= 230;
            }

        }
        ////////////
        else if (cb1.getSelectedItem().toString()=="Rangpur")
        {
            if (cb2.getSelectedItem().toString()=="Dhaka")
            {
                y= 293.4;
            }
            else if (cb2.getSelectedItem().toString()=="Brahmanbaria")
            {
                y= 373.2;
            }
            else if (cb2.getSelectedItem().toString()=="Bogra")
            {
                y= 106.3;
            }
            else if (cb2.getSelectedItem().toString()=="Gaibandha")
            {
                y= 74.4;
            }
            else if (cb2.getSelectedItem().toString()=="Noakhali")
            {
                y= 460.6;
            }
            else if (cb2.getSelectedItem().toString()=="Naogaon")
            {
                y= 151.1;
            }
            else if (cb2.getSelectedItem().toString()=="Pabna")
            {
                y= 227.8;
            }

        }

        s2=String.format("%.2f Km",y);
        out1.setText(s2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Distance_Calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Distance_Calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Distance_Calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Distance_Calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Distance_Calculate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JFormattedTextField out1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("td_logo.png")));
    }
}
